name: mcpvp
version: ${project.version}
main: me.skelouse.mcpvp.mcpvp
api-version: 1.13
authors: [skelouse, jakebrake11]
description: Minecraft mcpvp plugin
website: skelouse.com
commands:
  hg:
    description: Pulls up help menu for Hunger Games.
    usage: /<command>
  kit:
    description: Pulls up all available kits
    usage: /<command>